package com.master.univt.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

import java.io.Serializable;
import java.util.List;


// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User implements Serializable
{
  private static final long serialVersionUID = -6653450939813235814L;
  protected Long id;
  /** Not-null value. */
  protected String uId;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getuId() {
        return uId;
    }

    public void setuId(String uId) {
        this.uId = uId;
    }
}
