package com.master.univt.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BOOK_INFO.
 */
public class BookInfo {

    private Long id;
    private String title;
    private String authors;
    private String subtitle;
    private String printType;
    private String categories;
    private String contentVersion;
    private String imageLinks;
    private java.util.Date publishedDate;
    private java.util.Date pageCount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BookInfo() {
    }

    public BookInfo(Long id) {
        this.id = id;
    }

    public BookInfo(Long id, String title, String authors, String subtitle, String printType, String categories, String contentVersion, String imageLinks, java.util.Date publishedDate, java.util.Date pageCount) {
        this.id = id;
        this.title = title;
        this.authors = authors;
        this.subtitle = subtitle;
        this.printType = printType;
        this.categories = categories;
        this.contentVersion = contentVersion;
        this.imageLinks = imageLinks;
        this.publishedDate = publishedDate;
        this.pageCount = pageCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthors() {
        return authors;
    }

    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getPrintType() {
        return printType;
    }

    public void setPrintType(String printType) {
        this.printType = printType;
    }

    public String getCategories() {
        return categories;
    }

    public void setCategories(String categories) {
        this.categories = categories;
    }

    public String getContentVersion() {
        return contentVersion;
    }

    public void setContentVersion(String contentVersion) {
        this.contentVersion = contentVersion;
    }

    public String getImageLinks() {
        return imageLinks;
    }

    public void setImageLinks(String imageLinks) {
        this.imageLinks = imageLinks;
    }

    public java.util.Date getPublishedDate() {
        return publishedDate;
    }

    public void setPublishedDate(java.util.Date publishedDate) {
        this.publishedDate = publishedDate;
    }

    public java.util.Date getPageCount() {
        return pageCount;
    }

    public void setPageCount(java.util.Date pageCount) {
        this.pageCount = pageCount;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
