package com.master.univt.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession
{

  private final DaoConfig userDaoConfig;

  private final UserDao userDao;

  public DaoSession(final SQLiteDatabase db, final IdentityScopeType type,
    final Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap)
  {
    super(db);

    userDaoConfig = daoConfigMap.get(UserDao.class).clone();
    userDaoConfig.initIdentityScope(type);


    userDao = new UserDao(userDaoConfig, this);


    registerDao(User.class, userDao);

  }

  public void clear()
  {
    userDaoConfig.getIdentityScope().clear();

  }

  public void deleteAllData()
  {
    userDao.deleteAll();

  }

  public UserDao getUserDao()
  {
    return userDao;
  }


}
