package com.master.univt.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.master.univt.model.User;
import com.master.univt.model.Bookshelf;
import com.master.univt.model.BookInfo;
import com.master.univt.model.UserInfo;
import com.master.univt.model.SaleInfo;
import com.master.univt.model.AccessInfo;
import com.master.univt.model.Book;

import com.master.univt.model.UserDao;
import com.master.univt.model.BookshelfDao;
import com.master.univt.model.BookInfoDao;
import com.master.univt.model.UserInfoDao;
import com.master.univt.model.SaleInfoDao;
import com.master.univt.model.AccessInfoDao;
import com.master.univt.model.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig bookshelfDaoConfig;
    private final DaoConfig bookInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig saleInfoDaoConfig;
    private final DaoConfig accessInfoDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final UserDao userDao;
    private final BookshelfDao bookshelfDao;
    private final BookInfoDao bookInfoDao;
    private final UserInfoDao userInfoDao;
    private final SaleInfoDao saleInfoDao;
    private final AccessInfoDao accessInfoDao;
    private final BookDao bookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bookshelfDaoConfig = daoConfigMap.get(BookshelfDao.class).clone();
        bookshelfDaoConfig.initIdentityScope(type);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        saleInfoDaoConfig = daoConfigMap.get(SaleInfoDao.class).clone();
        saleInfoDaoConfig.initIdentityScope(type);

        accessInfoDaoConfig = daoConfigMap.get(AccessInfoDao.class).clone();
        accessInfoDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        bookshelfDao = new BookshelfDao(bookshelfDaoConfig, this);
        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        saleInfoDao = new SaleInfoDao(saleInfoDaoConfig, this);
        accessInfoDao = new AccessInfoDao(accessInfoDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Bookshelf.class, bookshelfDao);
        registerDao(BookInfo.class, bookInfoDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(SaleInfo.class, saleInfoDao);
        registerDao(AccessInfo.class, accessInfoDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        bookshelfDaoConfig.getIdentityScope().clear();
        bookInfoDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        saleInfoDaoConfig.getIdentityScope().clear();
        accessInfoDaoConfig.getIdentityScope().clear();
        bookDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BookshelfDao getBookshelfDao() {
        return bookshelfDao;
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public SaleInfoDao getSaleInfoDao() {
        return saleInfoDao;
    }

    public AccessInfoDao getAccessInfoDao() {
        return accessInfoDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
