package com.master.univt.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SALE_INFO.
 */
public class SaleInfo {

    private Long id;
    private String country;
    private String saleability;
    private String buyLink;
    private boolean isEbook;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SaleInfo() {
    }

    public SaleInfo(Long id) {
        this.id = id;
    }

    public SaleInfo(Long id, String country, String saleability, String buyLink, boolean isEbook) {
        this.id = id;
        this.country = country;
        this.saleability = saleability;
        this.buyLink = buyLink;
        this.isEbook = isEbook;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getSaleability() {
        return saleability;
    }

    public void setSaleability(String saleability) {
        this.saleability = saleability;
    }

    public String getBuyLink() {
        return buyLink;
    }

    public void setBuyLink(String buyLink) {
        this.buyLink = buyLink;
    }

    public boolean getIsEbook() {
        return isEbook;
    }

    public void setIsEbook(boolean isEbook) {
        this.isEbook = isEbook;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
